### ISSUE TITLE
major generation imperfections

### ISSUE THREAD

**Issue by balaramsudip** [orangeadam3/terra121#160]
I used the Terra 1-1 mod to go to manhattan, and the bay surrounding it doesn't exist. Also, there is a massive hole in the ground that I am sure didn't naturally generate, and there are no trees

**Comment by balaramsudip** [comment]
Now that I look at it, rivers don't naturally generate

**Comment by DavixDevelop** [comment]
The trees don't generate, because the TreeCover2000 is currently experiencing problems. For rivers to generate, you need to enable it when making a new world, advanced water (experimental). Also, the bay area seems to generate fine for me? Can you post the coordinates of this hole?
![Bay area](https://i.imgur.com/vASlxJr.png)

**Comment by balaramsudip** [comment]
After turning on experimental water, the entire manhattan is under water. The massive hole still exists.
![Screen Shot 2020-11-03 at 2 31 25 PM](https://user-images.githubusercontent.com/56773996/98047789-65574f80-1de1-11eb-9c14-4e24366b8f80.png)

**Comment by balaramsudip** [comment]
Also, rome is a mooshroom biome.

**Comment by DavixDevelop** [comment]
Um, I teleported to your coordinates, but as you can see I'm in the middle of the ocean. You sure you set up the right options when creating the save?
![Wt](https://i.imgur.com/5yQp1QL.jpg)

**Comment by balaramsudip** [comment]
I used the Equal Earth projection, and you may need to turn off shaders to be able to see it.

**Comment by vaporrrr** [comment]
You have to use the bteairocean projection/dymaxion edited
