### ISSUE TITLE
World Bugged

### ISSUE THREAD

**Issue by DaLagMan** [orangeadam3/terra121#31]
I have downloaded multiple versions of this mod and the world is a mushroom island chunk surrounded by water that goes really far down. Rest of the world is water. Also poor optimization.

**Comment by orangeadam3** [comment]
That is to be expected. The island is artificial null island (0N, 0W), there is nothing but ocean there in real life you need to use /tpll [latitude] [longitude] to go somewhere meaningful. Please refer to TROUBLESHOOT.MD in the future before reporting an issue.

I assume by "poor optimzation" you mean slow generation. Thats mostly unavoidable because the data is pulled from online datasources. The generation speed should be roughly tied to your internet speed.

**Comment by orangeadam3** [comment]
Try "/tpll 36.06600 -112.11720" without quotes. It's the Grand Canyon.
